
name: postfix_alias

services:

  postfix:
    restart: always
    container_name: postfix_alias
    ports:
      - "25:25"
    build: 
      context: ./postfix
      dockerfile: Dockerfile
    secrets:
      - virtual
      - mydestination


secrets:
  virtual:
    file: .secrets/virtual
  mydestination:
    file: .secrets/mydestination


